### ISSUE TITLE
RichHelpFormatter not working on Python 3.14.0b1

### ISSUE THREAD

**Issue by tleonhardt** [hamdanal/rich-argparse#163]
I help maintain the [cmd2](https://github.com/python-cmd2) open-source library and for the next version we have been working on incorporating `rich-argparse` to make our help output more aesthetically pleasing.

We recently added testing for Python `3.14-dev` to our GitHub Actions CI workflow and we are getting numerous unit test errors related to `RichHelpFormatter`.  The errors all look like the following

```sh
/opt/hostedtoolcache/Python/3.14.0-beta.1/x64/lib/python3.14/argparse.py:2729: in _get_formatter
    return self.formatter_class(
E   TypeError: RichHelpFormatter.__init__() got an unexpected keyword argument 'prefix_chars'
```

Looking at the [argparse documentation for Python 3.14](https://docs.python.org/3.14/library/argparse.html), I highly suspect this deprecation notice may be of relevance here:
> Deprecated since version 3.14: Passing [prefix_chars](https://docs.python.org/3.14/library/argparse.html#prefix-chars) to [add_argument_group()](https://docs.python.org/3.14/library/argparse.html#argparse.ArgumentParser.add_argument_group) is now deprecated.

**Comment by hamdanal** [comment]
This is a regression in the first beta of Python 3.14, it is already fixed on their main branch and the fix will be available for Python 3.14.0b2. To unblock CI now, please update rich-argparse to version 1.7.1 which I just uploaded to PyPI with the fix in #162.

**Comment by tleonhardt** [comment]
@hamdanal Thanks for your quick response and fix. Much appreciated. Feel free to close this from my perspective.
